# Notes:
## Missing values do not count towards percentages.

# Function definition
make_table_1 <- function(clinical){
    SMM <- clinical[clinical$disease_stage == 'SMM',]
    NDMM <- clinical[clinical$disease_stage == 'NDMM',]
    RRMM <- clinical[clinical$disease_stage == 'RRMM',]
    table_1 = data.frame(
        variable = c(
                'Number of patients',
                'Gender (male)*',
                'Age at sampling (years)**',
                'PC % on BM aspirate differential**',
                'PC % on BM biopsy**',
                'Monoclonal PC as % of WBC by flow of BM**',
                'Ig heavy chain*',
                'IgG',
                'IgA',
                'IgD',
                'None',
                'Ig light chain*',
                'Kappa',
                'Lambda',
                'None',
                'Serum M-spike (g/dl)**',
                'Involved s-FLC (mg/dl)**',
                'Ratio of involved to uninvolved s-FLC**'
        ),
        S = c(paste(nrow(SMM)),
              paste(count(SMM, gender)$n[2], ' (', 
                    round(count(SMM, gender)$n[2]/nrow(SMM)*100), '%)', sep=''),
              paste(median(SMM$age), ' (', 
                    quantile(SMM$age, probs = 0.25), '-',
                    quantile(SMM$age, probs = 0.75), ')', sep=''),
              paste(median(SMM$aspirate, na.rm = T), '% (', 
                    quantile(SMM$aspirate, probs = 0.25, na.rm = T), '-',
                    quantile(SMM$aspirate, probs = 0.75, na.rm = T), ')', sep=''),
              paste(median(SMM$biopsy, na.rm = T), '% (', 
                    quantile(SMM$biopsy, probs = 0.25, na.rm = T), '-',
                    quantile(SMM$biopsy, probs = 0.75, na.rm = T), ')', sep=''),
              paste(median(SMM$flow_PC, na.rm = T), '% (', 
                    quantile(SMM$flow_PC, probs = 0.25, na.rm = T), '-',
                    quantile(SMM$flow_PC, probs = 0.75, na.rm = T), ')', sep=''),
              NA,
              paste(nrow(SMM[SMM$IFE_heavy == 'IgG',]), ' (',
                    round(nrow(SMM[SMM$IFE_heavy == 'IgG',])/nrow(SMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(SMM[SMM$IFE_heavy == 'IgA',]), ' (',
                    round(nrow(SMM[SMM$IFE_heavy == 'IgA',])/nrow(SMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(SMM[SMM$IFE_heavy == 'IgD',]), ' (',
                    round(nrow(SMM[SMM$IFE_heavy == 'IgD',])/nrow(SMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(SMM[SMM$IFE_heavy == 'None',]), ' (',
                    round(nrow(SMM[SMM$IFE_heavy == 'None',])/nrow(SMM)*100,0), 
                    '%)', sep=''),
              NA,
              paste(nrow(SMM[SMM$FLC_involved_class == 'Kappa',]), ' (',
                    round(nrow(SMM[SMM$FLC_involved_class == 'Kappa',])/nrow(SMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(SMM[SMM$FLC_involved_class == 'Lambda',]), ' (',
                    round(nrow(SMM[SMM$FLC_involved_class == 'Lambda',])/nrow(SMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(SMM[SMM$FLC_involved_class == 'None',]), ' (',
                    round(nrow(SMM[SMM$FLC_involved_class == 'None',])/nrow(SMM)*100,0), 
                    '%)', sep=''),      
              paste(round(median(SMM$SPEP, na.rm = T),1), ' (', 
                    round(quantile(SMM$SPEP, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(SMM$SPEP, probs = 0.75, na.rm = T),1), ')', sep=''),
              paste(round(median(SMM$FLC_involved_value, na.rm = T),1), ' (', 
                    round(quantile(SMM$FLC_involved_value, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(SMM$FLC_involved_value, probs = 0.75, na.rm = T),1), ')', sep=''),
              paste(round(median(SMM$FLC_ratio, na.rm = T),1), ' (', 
                    round(quantile(SMM$FLC_ratio, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(SMM$FLC_ratio, probs = 0.75, na.rm = T),1), ')', sep='')
        ),
        N = c(paste(nrow(NDMM)),
              paste(count(NDMM, gender)$n[2], ' (', 
                    round(count(NDMM, gender)$n[2]/nrow(NDMM)*100), '%)', sep=''),
              paste(median(NDMM$age), ' (', 
                    quantile(NDMM$age, probs = 0.25), '-',
                    quantile(NDMM$age, probs = 0.75), ')', sep=''),
              paste(median(NDMM$aspirate, na.rm = T), '% (', 
                    quantile(NDMM$aspirate, probs = 0.25, na.rm = T), '-',
                    quantile(NDMM$aspirate, probs = 0.75, na.rm = T), ')', sep=''),
              paste(median(NDMM$biopsy, na.rm = T), '% (', 
                    quantile(NDMM$biopsy, probs = 0.25, na.rm = T), '-',
                    quantile(NDMM$biopsy, probs = 0.75, na.rm = T), ')', sep=''),
              paste(median(NDMM$flow_PC, na.rm = T), '% (', 
                    quantile(NDMM$flow_PC, probs = 0.25, na.rm = T), '-',
                    quantile(NDMM$flow_PC, probs = 0.75, na.rm = T), ')', sep=''),
              NA,
              paste(nrow(NDMM[NDMM$IFE_heavy == 'IgG',]), ' (',
                    round(nrow(NDMM[NDMM$IFE_heavy == 'IgG',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(NDMM[NDMM$IFE_heavy == 'IgA',]), ' (',
                    round(nrow(NDMM[NDMM$IFE_heavy == 'IgA',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(NDMM[NDMM$IFE_heavy == 'IgD',]), ' (',
                    round(nrow(NDMM[NDMM$IFE_heavy == 'IgD',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(NDMM[NDMM$IFE_heavy == 'None',]), ' (',
                    round(nrow(NDMM[NDMM$IFE_heavy == 'None',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),
              NA,
              paste(nrow(NDMM[NDMM$FLC_involved_class == 'Kappa',]), ' (',
                    round(nrow(NDMM[NDMM$FLC_involved_class == 'Kappa',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(NDMM[NDMM$FLC_involved_class == 'Lambda',]), ' (',
                    round(nrow(NDMM[NDMM$FLC_involved_class == 'Lambda',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(NDMM[NDMM$FLC_involved_class == 'None',]), ' (',
                    round(nrow(NDMM[NDMM$FLC_involved_class == 'None',])/nrow(NDMM)*100,0), 
                    '%)', sep=''),        
              paste(round(median(NDMM$SPEP, na.rm = T),1), ' (', 
                    round(quantile(NDMM$SPEP, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(NDMM$SPEP, probs = 0.75, na.rm = T),1), ')', sep=''),
              paste(round(median(NDMM$FLC_involved_value, na.rm = T),1), ' (', 
                    round(quantile(NDMM$FLC_involved_value, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(NDMM$FLC_involved_value, probs = 0.75, na.rm = T),1), ')', sep=''),
              paste(round(median(NDMM$FLC_ratio, na.rm = T),1), ' (', 
                    round(quantile(NDMM$FLC_ratio, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(NDMM$FLC_ratio, probs = 0.75, na.rm = T),1), ')', sep='')
        ),
        R = c(paste(nrow(RRMM)),
              paste(count(RRMM, gender)$n[2], ' (', 
                    round(count(RRMM, gender)$n[2]/nrow(RRMM)*100), '%)', sep=''),
              paste(median(RRMM$age), ' (', 
                    quantile(RRMM$age, probs = 0.25), '-',
                    quantile(RRMM$age, probs = 0.75), ')', sep=''),
              paste(median(RRMM$aspirate, na.rm = T), '% (', 
                    quantile(RRMM$aspirate, probs = 0.25, na.rm = T), '-',
                    quantile(RRMM$aspirate, probs = 0.75, na.rm = T), ')', sep=''),
              paste(median(RRMM$biopsy, na.rm = T), '% (', 
                    quantile(RRMM$biopsy, probs = 0.25, na.rm = T), '-',
                    quantile(RRMM$biopsy, probs = 0.75, na.rm = T), ')', sep=''),
              paste(median(RRMM$flow_PC, na.rm = T), '% (', 
                    quantile(RRMM$flow_PC, probs = 0.25, na.rm = T), '-',
                    quantile(RRMM$flow_PC, probs = 0.75, na.rm = T), ')', sep=''),
              NA,
              paste(nrow(RRMM[RRMM$IFE_heavy == 'IgG',]), ' (',
                    round(nrow(RRMM[RRMM$IFE_heavy == 'IgG',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(RRMM[RRMM$IFE_heavy == 'IgA',]), ' (',
                    round(nrow(RRMM[RRMM$IFE_heavy == 'IgA',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(RRMM[RRMM$IFE_heavy == 'IgD',]), ' (',
                    round(nrow(RRMM[RRMM$IFE_heavy == 'IgD',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(RRMM[RRMM$IFE_heavy == 'None',]), ' (',
                    round(nrow(RRMM[RRMM$IFE_heavy == 'None',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),
              NA,
              paste(nrow(RRMM[RRMM$FLC_involved_class == 'Kappa',]), ' (',
                    round(nrow(RRMM[RRMM$FLC_involved_class == 'Kappa',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(RRMM[RRMM$FLC_involved_class == 'Lambda',]), ' (',
                    round(nrow(RRMM[RRMM$FLC_involved_class == 'Lambda',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),
              paste(nrow(RRMM[RRMM$FLC_involved_class == 'None',]), ' (',
                    round(nrow(RRMM[RRMM$FLC_involved_class == 'None',])/nrow(RRMM)*100,0), 
                    '%)', sep=''),             
              paste(round(median(RRMM$SPEP, na.rm = T),1), ' (', 
                    round(quantile(RRMM$SPEP, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(RRMM$SPEP, probs = 0.75, na.rm = T),1), ')', sep=''),
              paste(round(median(RRMM$FLC_involved_value, na.rm = T),1), ' (', 
                    round(quantile(RRMM$FLC_involved_value, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(RRMM$FLC_involved_value, probs = 0.75, na.rm = T),1), ')', sep=''),
              paste(round(median(RRMM$FLC_ratio, na.rm = T),1), ' (', 
                    round(quantile(RRMM$FLC_ratio, probs = 0.25, na.rm = T),1), '-',
                    round(quantile(RRMM$FLC_ratio, probs = 0.75, na.rm = T),1), ')', sep='')
        ))

names(table_1) <- c(
        'Variable',
        'Smoldering multiple myeloma',
        'Newly diagnosed multiple myeloma',
        'Relapsing/refractory multiple myeloma'
        )
    return(table_1)
}